/**
 * SIH 2026 INTERNAL HACKATHON PORTAL - Data Repository
 * Co-Branded with AJK College of Arts & Science & AIIF (AJK Innovation Incubator Foundation)
 * Theme: "Observe. Analyze. Innovate." - SIH Problem Statement & Solution Collector
 */

// OPTIONAL: Paste your deployed Google Apps Script Web App URL below for 100% automated background email sending & Google Sheet logging
window.GOOGLE_APPS_SCRIPT_URL = "https://script.google.com/macros/s/AKfycbze3jE57qbhsPn00LHlPpgvt7GCKDlyw5dg-b5cFwZ9EmuyETeqDDodu90lwJJMQDYjwQ/exec";

const INITIAL_DATA = {
  branding: {
    portalTitle: "SIH 2026 INTERNAL HACKATHON",
    collegeName: "AJK College of Arts & Science",
    incubationCenter: "AIIF (AJK Innovation Incubator Foundation)",
    tagline: "WORLD'S 1ST ETHNIC INCUBATOR",
    recognition: "Recognized by StartupTN Under SIGrant",
    theme: "Observe. Analyze. Innovate.",
    academicYear: "2026 - 2027",
    primaryColor: "#00a859",
    secondaryColor: "#1e3a8a",
    venue: "AJK College Campus",
    dates: "Registration Deadline: Sep 5, 2026 | Internal Pitching & Shortlisting: Sep 9, 2026",
    targetShortlist: 50,
    minTeamsPerDept: 2
  },

  // 23 Official Departments / Courses at AJK College of Arts & Science
  departments: [
    { id: 1, name: "B.Sc Artificial Intelligence & Machine Learning", code: "B.Sc AI & ML", target: 2 },
    { id: 2, name: "B.Sc Digital & Cyber Forensic Science", code: "B.Sc Cyber Forensic", target: 2 },
    { id: 3, name: "B.Sc Computer Science with Data Analytics", code: "B.Sc CS DA", target: 2 },
    { id: 4, name: "BCA", code: "BCA", target: 2 },
    { id: 5, name: "BCA Artificial Intelligence", code: "BCA AI", target: 2 },
    { id: 6, name: "BCA Augmented Reality & Virtual Reality", code: "BCA AR & VR", target: 2 },
    { id: 7, name: "B.Sc Computer Science", code: "B.Sc CS", target: 2 },
    { id: 8, name: "B.Sc Biotechnology", code: "B.Sc Biotech", target: 2 },
    { id: 9, name: "B.Sc Forensic Science", code: "B.Sc Forensic", target: 2 },
    { id: 10, name: "B.COM CA", code: "B.Com CA", target: 2 },
    { id: 11, name: "BBA CA", code: "BBA CA", target: 2 },
    { id: 12, name: "BBA Aviation Management", code: "BBA Aviation", target: 2 },
    { id: 13, name: "BBA Logistics & Supply Chain Management", code: "BBA Logistics", target: 2 },
    { id: 14, name: "B.Sc Catering Science & Hotel Management", code: "B.Sc CSHM", target: 2 },
    { id: 15, name: "B.Sc Costume Design & Fashion", code: "B.Sc CDF", target: 2 },
    { id: 16, name: "B.Sc Visual Communication & Electronics Media", code: "B.Sc Viscom", target: 2 },
    { id: 17, name: "BCA Cybersecurity with Data Science", code: "BCA Cyber & DS", target: 2 },
    { id: 18, name: "BBA Logistics with Finance", code: "BBA Finance", target: 2 },
    { id: 19, name: "BBA Aviation with Hospitality Management", code: "BBA Hospitality", target: 2 },
    { id: 20, name: "M.Sc Cyber Security", code: "M.Sc Cyber Security", target: 2 },
    { id: 21, name: "M.Sc Computer Science", code: "M.Sc CS", target: 2 },
    { id: 22, name: "M.Com", code: "M.Com", target: 2 },
    { id: 23, name: "MBA", code: "MBA", target: 2 }
  ],

  sdgs: [
    { id: 1, title: "No Poverty", color: "#E5243B", icon: "🤝", desc: "End poverty in all its forms everywhere." },
    { id: 2, title: "Zero Hunger", color: "#DDA63A", icon: "🌾", desc: "End hunger, achieve food security and improved nutrition." },
    { id: 3, title: "Good Health & Well-Being", color: "#4C9F38", icon: "🩺", desc: "Ensure healthy lives and promote well-being for all." },
    { id: 4, title: "Quality Education", color: "#C5192D", icon: "🎓", desc: "Ensure inclusive and equitable quality education." },
    { id: 5, title: "Gender Equality", color: "#FF3A21", icon: "⚖️", desc: "Achieve gender equality and empower all women and girls." },
    { id: 6, title: "Clean Water & Sanitation", color: "#26BDE2", icon: "💧", desc: "Ensure availability and sustainable management of water." },
    { id: 7, title: "Affordable & Clean Energy", color: "#FCC30B", icon: "⚡", desc: "Ensure access to affordable, reliable, sustainable energy." },
    { id: 8, title: "Decent Work & Economic Growth", color: "#A21942", icon: "📈", desc: "Promote sustained, inclusive and sustainable economic growth." },
    { id: 9, title: "Industry, Innovation & Infrastructure", color: "#FD6925", icon: "🏗️", desc: "Build resilient infrastructure, foster innovation." },
    { id: 10, title: "Reduced Inequalities", color: "#DD1367", icon: "🌐", desc: "Reduce inequality within and among countries." },
    { id: 11, title: "Sustainable Cities & Communities", color: "#FD9D24", icon: "🏙️", desc: "Make cities inclusive, safe, resilient and sustainable." },
    { id: 12, title: "Responsible Consumption & Production", color: "#BF8B2E", icon: "♻️", desc: "Ensure sustainable consumption and production patterns." },
    { id: 13, title: "Climate Action", color: "#3F7E44", icon: "🌍", desc: "Take urgent action to combat climate change and its impacts." },
    { id: 14, title: "Life Below Water", color: "#0A97D9", icon: "🌊", desc: "Conserve and sustainably use oceans, seas and marine resources." },
    { id: 15, title: "Life on Land", color: "#56C02B", icon: "🌱", desc: "Protect, restore and promote sustainable use of terrestrial ecosystems." },
    { id: 16, title: "Peace, Justice & Strong Institutions", color: "#00689D", icon: "🕊️", desc: "Promote peaceful and inclusive societies for sustainable development." },
    { id: 17, title: "Partnerships for the Goals", color: "#19486A", icon: "🤝", desc: "Strengthen the means of implementation and revitalize global partnership." }
  ],

  mentors: [],

  // OFFICIAL SIH 2026 PROBLEM STATEMENTS (Exact SIH Portal Table Format: SIH26001, SIH26002, etc.)
  problemStatements: [
    {
      sNo: 1,
      id: "SIH26001",
      title: "AI-Based early warning and landslide Risk Monitoring System in NER",
      category: "Software",
      organization: "Ministry of Development of North Eastern Region (MDoNER)",
      theme: "Disaster Management",
      deadline: "20 September 2026",
      submittedCount: "0/500",
      description: "Deployment of AI/ML predictive risk monitoring for landslide-prone terrains in North Eastern Region with LoRa telemetry and real-time community alerts.",
      techStack: ["Python ML", "GIS Telemetry", "LoRaWAN", "FastAPI"]
    },
    {
      sNo: 2,
      id: "SIH26002",
      title: "AI-Based Smart Logistics and Accessibility Intelligence Platform for North Eastern Region (NER)",
      category: "Software",
      organization: "Ministry of Development of North Eastern Region (MDoNER)",
      theme: "Smart Automation",
      deadline: "20 September 2026",
      submittedCount: "0/500",
      description: "Route optimization, terrain accessibility prediction, and supply chain tracking for hill logistics.",
      techStack: ["React Native", "Python", "Google Maps API", "PostgreSQL"]
    },
    {
      sNo: 3,
      id: "SIH26003",
      title: "AI-Based Cognitive Gaming and Memory Assistance Platform for Elderly Dementia Patients in North Eastern Region (NER)",
      category: "Software",
      organization: "Ministry of Development of North Eastern Region (MDoNER)",
      theme: "Space Technology",
      deadline: "20 September 2026",
      submittedCount: "0/500",
      description: "Adaptive cognitive training exercises, voice memory prompts, and remote caregiver telemetry for dementia care.",
      techStack: ["Flutter", "TensorFlow Lite", "WebRTC", "Node.js"]
    },
    {
      sNo: 4,
      id: "SIH26004",
      title: "AI-Assisted Early Detection System for Osteoarthritis (OA) Risk Markers in North Eastern Region (NER)",
      category: "Hardware",
      organization: "Ministry of Development of North Eastern Region (MDoNER)",
      theme: "Space Technology",
      deadline: "20 September 2026",
      submittedCount: "0/500",
      description: "Wearable acoustic/gait sensor array detecting early biomechanical OA risk markers with edge ML.",
      techStack: ["ESP32 / Wearable Sensors", "Edge Impulse ML", "Bluetooth LE"]
    },
    {
      sNo: 5,
      id: "SIH26005",
      title: "Solar-Powered Smart Mini Cold Storage System for Fresh Vegetables in North Eastern Region (NER)",
      category: "Hardware",
      organization: "Ministry of Development of North Eastern Region (MDoNER)",
      theme: "Smart Vehicles",
      deadline: "20 September 2026",
      submittedCount: "0/500",
      description: "Off-grid solar Peltier cold storage box for small farmers with IoT temperature and humidity telemetry.",
      techStack: ["Peltier Cooling", "Arduino Mega", "Solar Rig", "GSM Telemetry"]
    },
    {
      sNo: 6,
      id: "SIH26006",
      title: "Smart Counterfeit Drug Identification & Blockchain Supply Chain Verification",
      category: "Software",
      organization: "Ministry of Health & Family Welfare",
      theme: "MedTech & Healthcare",
      deadline: "20 September 2026",
      submittedCount: "0/500",
      description: "Mobile scanning portal allowing citizens to scan pharmaceutical QR codes linked to an immutable blockchain ledger verifying manufacturer batch authenticity.",
      techStack: ["Solidity", "Ethereum", "React Native", "Node.js"]
    },
    {
      sNo: 7,
      id: "SIH26007",
      title: "AI Powered Dynamic Traffic Signal Control & Emergency Vehicle Routing",
      category: "Software",
      organization: "Ministry of Road Transport & Highways",
      theme: "Smart Automation",
      deadline: "20 September 2026",
      submittedCount: "0/500",
      description: "Real-time intersection computer vision feed estimating vehicle queue density and dynamically clearing emergency vehicles.",
      techStack: ["Python", "YOLOv8", "OpenCV", "MQTT"]
    },
    {
      sNo: 8,
      id: "SIH26008",
      title: "Automated Dry/Wet Segregation & Smart Bin Telemetry Upgrade Kit",
      category: "Hardware",
      organization: "Ministry of Housing and Urban Affairs",
      theme: "Environment & Waste Mgmt",
      deadline: "20 September 2026",
      submittedCount: "0/500",
      description: "Smart bin upgrade kit using optical/capacitive sensors to automatically route dry vs wet garbage and send GSM fill alerts.",
      techStack: ["Arduino Mega", "Optical Sensors", "GSM Module", "Servo"]
    },
    {
      sNo: 9,
      id: "SIH26009",
      title: "Smart IoT Water Quality Monitoring Sensor Node for Rural Lakes",
      category: "Hardware",
      organization: "Ministry of Jal Shakti",
      theme: "Clean Water & Sanitation",
      deadline: "20 September 2026",
      submittedCount: "0/500",
      description: "Submersible buoy node monitoring pH, TDS, and turbidity pushing telemetry alerts to local Panchayats when water safety thresholds cross.",
      techStack: ["ESP32", "pH & TDS Sensors", "Solar Buoy", "LoRaWAN"]
    },
    {
      sNo: 10,
      id: "SIH26010",
      title: "Voice & Multilingual Legal Document Simplifier for Citizens",
      category: "Software",
      organization: "Ministry of Law and Justice",
      theme: "Governance & Inclusion",
      deadline: "20 September 2026",
      submittedCount: "0/500",
      description: "AI voice translation portal simplifying complex legal land and welfare notices into vernacular Tamil, Hindi, and English.",
      techStack: ["Python", "Whisper Speech API", "LangChain", "React"]
    }
  ],

  // Clean empty array for student submissions
  teams: [
    {
        "sno": 1,
        "team_id": "SIH-TEAM-13",
        "team_name": "Neural Ninjas",
        "leader_name": "SREYAS KALLAZHI",
        "mentor_name": "Mr. V. Muthusaravanan",
        "department": "BCA Artificial Intelligence",
        "email": "sreyaskallazhi2425@ajkcas.com",
        "roll": "24UGAL051",
        "category": "Software",
        "ps": "[SIH26012] AI-Based Automated Urban Parcel Mapping and Cadastral Feature Extraction System using Drone lmagery"
    },
    {
        "sno": 2,
        "team_id": "SIH-TEAM-17",
        "team_name": "Byte Brains",
        "leader_name": "SRUTHI B",
        "mentor_name": "Mrs. K. Shiny",
        "department": "BCA Artificial Intelligence",
        "email": "sruthib2425@ajkcas.com",
        "roll": "24UGAL053",
        "category": "Software",
        "ps": "[SIH26028] Dynamic Forecast of Expected Time of Arrival (ETA) for Coaching Trains"
    },
    {
        "sno": 3,
        "team_id": "SIH-TEAM-03",
        "team_name": "TechFront",
        "leader_name": "Krishna Theertha S",
        "mentor_name": "Dr John gracias",
        "department": "B.Sc Computer Science",
        "email": "krishnatheerthas2526@ajkcas.com",
        "roll": "25UGCS018",
        "category": "Software",
        "ps": "[SIH26032] Digital Platform for Efficient Agricultural Procurement, Slot Booking and Queue Management\u201d"
    },
    {
        "sno": 4,
        "team_id": "SIH-TEAM-03-A",
        "team_name": "Keratin (Idea 1)",
        "leader_name": "SAMSHEER.K",
        "mentor_name": "Dr.V.LOGESHWARAN",
        "department": "B.Sc Biotechnology",
        "email": "samsheer473@gmail.com",
        "roll": "25UGBT007",
        "category": "Hardware",
        "ps": "[SIH26217] Development of Sustainable Keratin-Based Bioplastic from Chicken Feather Waste"
    },
    {
        "sno": 5,
        "team_id": "SIH-TEAM-03-B",
        "team_name": "Keratin (Idea 2)",
        "leader_name": "SAMSHEER.K",
        "mentor_name": "Dr.V.LOGESHWARAN",
        "department": "B.Sc Biotechnology",
        "email": "samsheer473@gmail.com",
        "roll": "25UGBT007",
        "category": "Hardware",
        "ps": "[SIH26040] FeatherClean: Development of a Sustainable Bioadsorbent from Chicken Feather Waste for Textile Wastewater Treatment"
    },
    {
        "sno": 6,
        "team_id": "SIH-TEAM-06",
        "team_name": "Cyclone Guardians",
        "leader_name": "Arun N",
        "mentor_name": "Dr. Vineetha Vijayan",
        "department": "B.Sc Artificial Intelligence & Machine Learning",
        "email": "arunn2425@ajkcas.com",
        "roll": "24UGAI012",
        "category": "Software",
        "ps": "[26070] To develop an Artificial Intelligence (AI) / Machine Learning (ML) based system for identification, classification, and prediction of different tropical cyclone patterns using multi-source satellite data."
    },
    {
        "sno": 7,
        "team_id": "SIH-TEAM-01-B",
        "team_name": "Cascaders (Idea 2)",
        "leader_name": "Abhishek Shaji",
        "mentor_name": "Dr. Vineetha Vijayan",
        "department": "B.Sc Artificial Intelligence & Machine Learning",
        "email": "abhishekshaji2526@ajkcas.com",
        "roll": "25UGAI003",
        "category": "Software",
        "ps": "[SIH26101] Al-Enabled Learning Platform for Skill-Gap Analysis & Auto-MCQ Generation"
    },
    {
        "sno": 8,
        "team_id": "SIH-TEAM-01-A",
        "team_name": "Cascaders (Idea 1)",
        "leader_name": "Abhishek Shaji",
        "mentor_name": "Dr. Vineetha Vijayan",
        "department": "B.Sc Artificial Intelligence & Machine Learning",
        "email": "abhishekshaji2526@ajkcas.com",
        "roll": "25UGAI003",
        "category": "Software",
        "ps": "[SIH26162] Al Detection/Classification  of Industrial Fires via Satellite Data"
    },
    {
        "sno": 9,
        "team_id": "SIH-TEAM-06-B",
        "team_name": "KRATOS (Idea 2)",
        "leader_name": "MADHUMITHRA K",
        "mentor_name": "SANGEETHA SR",
        "department": "BCA",
        "email": "madhumithrak2526@ajkcas.com",
        "roll": "25UGCA026",
        "category": "Software",
        "ps": "[SIH26135] Difficulties in tracking employment outcomes, skill gaps, and the impact of skilling initiatives"
    },
    {
        "sno": 10,
        "team_id": "SIH-TEAM-06-A",
        "team_name": "KRATOS (Idea 1)",
        "leader_name": "MADHUMITHRA K",
        "mentor_name": "SANGEETHA SR",
        "department": "BCA",
        "email": "madhumithrak2526@ajkcas.com",
        "roll": "25UGCA026",
        "category": "Software",
        "ps": "[SIH26044] Portal for Academia - Industry collaboration for Skill Mapping, Internships and Placement"
    },
    {
        "sno": 11,
        "team_id": "SIH-TEAM-01",
        "team_name": "Neerav fighters",
        "leader_name": "Srijin Krishna",
        "mentor_name": "Pavithra V",
        "department": "BCA",
        "email": "srijinkrishna2425@ajkcas.com",
        "roll": "24UGCA050",
        "category": "Software",
        "ps": "[26028] ETA"
    },
    {
        "sno": 12,
        "team_id": "SIH-TEAM-12-B",
        "team_name": "Team flash (Idea 2)",
        "leader_name": "Abhinav ks",
        "mentor_name": "Moushika",
        "department": "BCA",
        "email": "abhinavksbca2526@ajkcas.com",
        "roll": "25UGCA057",
        "category": "Software",
        "ps": "[SOLVE ALL PROBLEMS] Same as 1"
    },
    {
        "sno": 13,
        "team_id": "SIH-TEAM-13-A",
        "team_name": "Team flash (Idea 1)",
        "leader_name": "Abhinav ks",
        "mentor_name": "Moushika",
        "department": "BCA",
        "email": "abhinavksbca2526@ajkcas.com",
        "roll": "25UGCA057",
        "category": "Software",
        "ps": "[333] Flash speed work"
    },
    {
        "sno": 14,
        "team_id": "SIH-TEAM-14",
        "team_name": "Hacksmiths",
        "leader_name": "Shamil Ahmed",
        "mentor_name": "Kishor r",
        "department": "BCA",
        "email": "shamilahmed2627@ajkcas.com",
        "roll": "5998",
        "category": "Software",
        "ps": "[SIH26068] WeatherGPT: Conversational AI for Weather Forecasting, Alerts, and Climate Information"
    },
    {
        "sno": 15,
        "team_id": "SIH-TEAM-15",
        "team_name": "Cyber Titans",
        "leader_name": "Ajith Tm",
        "mentor_name": "Kishor R",
        "department": "BCA",
        "email": "ajithtm2627@ajkcas.com",
        "roll": "5830",
        "category": "Software",
        "ps": "[SIH26018] Intelligent Land Record Digitization and Validation System"
    },
    {
        "sno": 16,
        "team_id": "SIH-TEAM-16",
        "team_name": "VISION_X",
        "leader_name": "NIMISHA RAMESH R",
        "mentor_name": "SHABNA RASHEED",
        "department": "BCA",
        "email": "nimisharameshr2627@ajkcas.com",
        "roll": "5535",
        "category": "Software",
        "ps": "[SIH26068] WeatherGPT: Conversational AI for Weather Forecasting, Alerts, and Climate Information"
    },
    {
        "sno": 17,
        "team_id": "SIH-TEAM-17-1",
        "team_name": "InnovateX",
        "leader_name": "POOJA KRISHNA C T",
        "mentor_name": "SHABNA RASHEED",
        "department": "BCA",
        "email": "poojakrishnact2627@ajkcas.com",
        "roll": "6029",
        "category": "Software",
        "ps": "[SIH26205] Student Innovation-Submit your ideas to address the growing pressures on the city\u2019s resources, transport networks, and logistic infrastructure."
    },
    {
        "sno": 18,
        "team_id": "SIH-TEAM-18-B",
        "team_name": "Team_Nandithazz (Idea 2)",
        "leader_name": "Nanditha j Chandran",
        "mentor_name": "Moushika D",
        "department": "BCA",
        "email": "nandithajchandran2526@ajkcas.com",
        "roll": "25UGCA095",
        "category": "Software",
        "ps": "[SIH26007] Safe and Efficient operation of mine vehicles in fog and Low visibility conditions in open cast iron ore mines"
    },
    {
        "sno": 19,
        "team_id": "SIH-TEAM-19-A",
        "team_name": "Team_Nandithazz (Idea 1)",
        "leader_name": "Nanditha j Chandran",
        "mentor_name": "Moushika D",
        "department": "BCA",
        "email": "nandithajchandran2526@ajkcas.com",
        "roll": "25UGCA095",
        "category": "Software",
        "ps": "[SIH26005] Solar-powered smart mini cold storage system for fresh vegetables in north Eastern region (NER)"
    },
    {
        "sno": 20,
        "team_id": "SIH-TEAM-20",
        "team_name": "Infinity 6",
        "leader_name": "Mishab M",
        "mentor_name": "Sangeetha  SR",
        "department": "BCA",
        "email": "mishabm2526@ajkcas.com",
        "roll": "25UGCA027",
        "category": "Software",
        "ps": "[SIH26192] Flash Flood Prediction System for Hilly Regions using Multi-Source Data Theme"
    },
    {
        "sno": 21,
        "team_id": "SIH-TEAM-21",
        "team_name": "Insight squad",
        "leader_name": "Krishnapriya. K. U",
        "mentor_name": "Tarun Richard",
        "department": "MBA",
        "email": "krishnapriyakv2627@ajkcas.com",
        "roll": "5503",
        "category": "Hardware",
        "ps": "[SIH26223] Student Innovation-Disaster management includes ideas related to risk mitigation, Planning and management before, after or during a disaster."
    },
    {
        "sno": 22,
        "team_id": "SIH-TEAM-22-B",
        "team_name": "IdeaHub (Idea 2)",
        "leader_name": "Muhammed Irfan kv",
        "mentor_name": "Tarun",
        "department": "MBA",
        "email": "muhammedirfan@ajkcas.com",
        "roll": "6095",
        "category": "Hardware",
        "ps": "[SIH26213] Fitness and sports"
    },
    {
        "sno": 23,
        "team_id": "SIH-TEAM-22-A",
        "team_name": "IdeaHub (Idea 1)",
        "leader_name": "Muhammed Irfan kv",
        "mentor_name": "Tarun",
        "department": "MBA",
        "email": "muhammedirfan@ajkcas.com",
        "roll": "6095",
        "category": "Hardware",
        "ps": "[SIH225] Toys and games"
    },
    {
        "sno": 24,
        "team_id": "SIH-TEAM-24-A",
        "team_name": "Hexacode (Idea 1)",
        "leader_name": "Anusree S",
        "mentor_name": "Moushika. D",
        "department": "BCA",
        "email": "anusrees2526@ajkcas.com",
        "roll": "25UGCA075",
        "category": "Software",
        "ps": "[SIH26085] Disaster Management"
    },
    {
        "sno": 25,
        "team_id": "SIH-TEAM-24-B",
        "team_name": "Hexacode (Idea 2)",
        "leader_name": "Anusree S",
        "mentor_name": "Moushika. D",
        "department": "BCA",
        "email": "anusrees2526@ajkcas.com",
        "roll": "25UGCA075",
        "category": "Software",
        "ps": "[SIH26076] Smart Automation"
    },
    {
        "sno": 26,
        "team_id": "SIH-TEAM-26",
        "team_name": "Future Executives",
        "leader_name": "Manjima Muralidharan",
        "mentor_name": "Mr. Tarun Richard",
        "department": "MBA",
        "email": "manjimamuralidharanm2627@ajkcas.com",
        "roll": "6271",
        "category": "Hardware",
        "ps": "[SIH26221] Student Innovation: A solution/idea that can boost the current situation of the industry including hotels, travel and others."
    },
    {
        "sno": 27,
        "team_id": "SIH-TEAM-27",
        "team_name": "Code crew",
        "leader_name": "K.K.Soorya",
        "mentor_name": "Mrs.Greeshma",
        "department": "BCA",
        "email": "kksoorya2425@ajkcas.com",
        "roll": "24UGCA077",
        "category": "Software",
        "ps": "[SIH26044] Smart Automation"
    },
    {
        "sno": 28,
        "team_id": "SIH-TEAM-28-A",
        "team_name": "Layyarri (Idea 1)",
        "leader_name": "Rihan",
        "mentor_name": "Layyarri",
        "department": "BBA Logistics & Supply Chain Management",
        "email": "mohammedrihan2627@ajkcas.com",
        "roll": "5811",
        "category": "Software",
        "ps": "[LYR267] Logistics"
    },
    {
        "sno": 29,
        "team_id": "SIH-TEAM-28-B",
        "team_name": "Layyarri (Idea 2)",
        "leader_name": "Rihan",
        "mentor_name": "Layyarri",
        "department": "BBA Logistics & Supply Chain Management",
        "email": "mohammedrihan2627@ajkcas.com",
        "roll": "5811",
        "category": "Software",
        "ps": "[LYR267] Logistics"
    },
    {
        "sno": 30,
        "team_id": "SIH-TEAM-30-B",
        "team_name": "Logizz innovators (Idea 2)",
        "leader_name": "W.jemima vasanthy",
        "mentor_name": "Dr.poornima G",
        "department": "BBA Logistics & Supply Chain Management",
        "email": "wjemimavasanthy2627@ajkcas.com",
        "roll": "5567",
        "category": "Software",
        "ps": "[SIH26002] Al-Based Smart Logistics and Accessibility Intelligence Platform for North Eastern Region (NER)"
    },
    {
        "sno": 31,
        "team_id": "SIH-TEAM-30-A",
        "team_name": "Logizz innovators (Idea 1)",
        "leader_name": "W.jemima vasanthy",
        "mentor_name": "Dr.poornima G",
        "department": "BBA Logistics & Supply Chain Management",
        "email": "wjemimavasanthy2627@ajkcas.com",
        "roll": "5567",
        "category": "Software",
        "ps": "[SIH26006] Transportation and logistics"
    },
    {
        "sno": 32,
        "team_id": "SIH-TEAM-32-B",
        "team_name": "TEAM NEXORA (Idea 2)",
        "leader_name": "S. Mithyleash",
        "mentor_name": "ASHA K",
        "department": "B.Sc Forensic Science",
        "email": "mithyleashs2425@ajkcas.com",
        "roll": "24UGFS015",
        "category": "Hardware",
        "ps": "[SIH26214] Student Innovation-Ideas that showcase the rich cultural heritage and traditions of India."
    },
    {
        "sno": 33,
        "team_id": "SIH-TEAM-32-A",
        "team_name": "TEAM NEXORA (Idea 1)",
        "leader_name": "S. Mithyleash",
        "mentor_name": "ASHA K",
        "department": "B.Sc Forensic Science",
        "email": "mithyleashs2425@ajkcas.com",
        "roll": "24UGFS015",
        "category": "Hardware",
        "ps": "[SIH26039] Al-Powered Underground Mine Safety, Monitoring and Rescue System."
    },
    {
        "sno": 34,
        "team_id": "SIH-TEAM-34",
        "team_name": "Hacktivators",
        "leader_name": "Praveen K P",
        "mentor_name": "Mrs.Greeshma R",
        "department": "BCA",
        "email": "praveenkpsuresh@gmail.com",
        "roll": "24UGCA083",
        "category": "Software",
        "ps": "[SIH26003] Al-Based Cognitive Gaming and Memory Assistance Platform for Elderly Dementia Patients in North Eastern Region (NER)"
    },
    {
        "sno": 35,
        "team_id": "SIH-TEAM-35",
        "team_name": "Survey team",
        "leader_name": "Athira.S",
        "mentor_name": "Dr mamta",
        "department": "BBA CA",
        "email": "athiras2526@ajkcas.com",
        "roll": "25UGBC019",
        "category": "Hardware",
        "ps": "[SIH26010] Survey based"
    },
    {
        "sno": 36,
        "team_id": "SIH-TEAM-36",
        "team_name": "Jumail Team",
        "leader_name": "Dharshan R",
        "mentor_name": "Dr.Mamta",
        "department": "BBA CA",
        "email": "rdharshan2526@ajkcs.com",
        "roll": "25UGBC023",
        "category": "Hardware",
        "ps": "[SIH26040] Smart Water Purification and Quality Monitoring System for Rural and Mining-Affected Areas."
    },
    {
        "sno": 37,
        "team_id": "SIH-TEAM-37",
        "team_name": "Proton",
        "leader_name": "Abhinav s",
        "mentor_name": "Mr.S.R.DHARAN",
        "department": "B.Sc Computer Science with Data Analytics",
        "email": "abhinavs2526@ajkcas.com",
        "roll": "25UGDA003",
        "category": "Software",
        "ps": "[SIH26044] Portal for Academia - Industry collaboration for Skill Mapping, Internships and  Placement"
    },
    {
        "sno": 38,
        "team_id": "SIH-TEAM-38",
        "team_name": "ROYAL COMMERCE",
        "leader_name": "AFRA I",
        "mentor_name": "MS.KRISHNAVENI S",
        "department": "B.COM CA",
        "email": "afrai2526@ajkcas.com",
        "roll": "25UGPA001",
        "category": "Hardware",
        "ps": "[SIH26223] Student Innovation-Disaster management includes ideas related to risk mitigation, Planning and management before, after or during a disaster."
    },
    {
        "sno": 39,
        "team_id": "SIH-TEAM-39",
        "team_name": "Aeros Innovators",
        "leader_name": "Shefin M",
        "mentor_name": "Rekha Ramachandran",
        "department": "BBA Aviation Management",
        "email": "shefinm2627@ajkcas.com",
        "roll": "AJKTEMP0043",
        "category": "Software",
        "ps": "[SIH26056] Smart Automation"
    },
    {
        "sno": 40,
        "team_id": "SIH-TEAM-40-A",
        "team_name": "The InnoCrew (Idea 1)",
        "leader_name": "Prajesh K",
        "mentor_name": "Rekha Ramachandran",
        "department": "BBA Aviation Management",
        "email": "prajeshk2627@ajkcas.com",
        "roll": "AJKTEMP0164",
        "category": "Software",
        "ps": "[SIH26007] Development of an Intelligent Freight Forecasting 0/500 Transpc & Logist Model for Optimized Vesse/ Chartering and bulk cargo Procurement from overseas 7 to East Coast of Steel India / smart automation"
    },
    {
        "sno": 41,
        "team_id": "SIH-TEAM-40-B",
        "team_name": "The InnoCrew (Idea 2)",
        "leader_name": "Prajesh K",
        "mentor_name": "Rekha Ramachandran",
        "department": "BBA Aviation Management",
        "email": "prajeshk2627@ajkcas.com",
        "roll": "AJKTEMP0164",
        "category": "Software",
        "ps": "[SIH26002] Al-Based Smart Logistics and Accessibility Intelligence Platform for North Eastern Region (NER) Transportation & logistics"
    },
    {
        "sno": 42,
        "team_id": "SIH-TEAM-42-B",
        "team_name": "Innoverse (Idea 2)",
        "leader_name": "Sajela thasni m.p",
        "mentor_name": "Regha ramachandran",
        "department": "BBA Aviation Management",
        "email": "sajelathasnimp2627@ajkcas.com",
        "roll": "AJKTEMP01 B7",
        "category": "Software",
        "ps": "[SIH26004\t0/500] Al-Assisted Early Detection System for Osteoarthritis (OA) Risk Markers in North Eastern Region (NER)"
    },
    {
        "sno": 43,
        "team_id": "SIH-TEAM-42-A",
        "team_name": "Innoverse (Idea 1)",
        "leader_name": "Sajela thasni m.p",
        "mentor_name": "Regha ramachandran",
        "department": "BBA Aviation Management",
        "email": "sajelathasnimp2627@ajkcas.com",
        "roll": "AJKTEMP01 B7",
        "category": "Software",
        "ps": "[SIH26003/0/500] AI-Based Cognitive Gaming and Memory Assistance Platform for Elderly Dementia Patients in North Eastern Region (NER)"
    },
    {
        "sno": 44,
        "team_id": "SIH-TEAM-50",
        "team_name": "Aero Ambassadors",
        "leader_name": "N Maheshwari",
        "mentor_name": "Punitha D",
        "department": "BBA Aviation with Hospitality Management",
        "email": "nmaheshwari2627@ajkcas.com",
        "roll": "5611",
        "category": "Hardware",
        "ps": "[SIH26221] Student Innovation-A solution/idea that can boost the current situation of the tourism industries including hotels, travel and others"
    },
    {
        "sno": 45,
        "team_id": "SIH-TEAM-51",
        "team_name": "Solar Frost",
        "leader_name": "Harisath Anandha kumar",
        "mentor_name": "Hema Priyan",
        "department": "B.Sc Catering Science & Hotel Management",
        "email": "harisathanandhakumar2526@ajkcas.com",
        "roll": "25UGHM018",
        "category": "Hardware",
        "ps": "[SIH 26005] Solar powered smart mini cold refrigerator to storege system for fresh vegetable in North eastern area"
    },
    {
        "sno": 46,
        "team_id": "SIH-TEAM-52",
        "team_name": "Sky & Service",
        "leader_name": "R Ajith",
        "mentor_name": "Punitha D",
        "department": "BBA Aviation Management",
        "email": "ajiths2627@ajkcas.com",
        "roll": "5951",
        "category": "Software",
        "ps": "[SIH26056] Development of a Real-time Airfare Price Index for India through Automated Web Scraping of Airline and Online Travel Aggregator Portals for Augmentation of the Consumer Price Index (CPI)."
    },
    {
        "sno": 47,
        "team_id": "SIH-TEAM-53-A",
        "team_name": "NEXUS (Idea 1)",
        "leader_name": "ARISH M",
        "mentor_name": "KISHORE K",
        "department": "B.Sc Digital & Cyber Forensic Science",
        "email": "arishm2425@ajkcas.com",
        "roll": "24UGDC002",
        "category": "Software",
        "ps": "[SIH26160] Block chain & Cyber Security"
    },
    {
        "sno": 48,
        "team_id": "SIH-TEAM-53-B",
        "team_name": "NEXUS (Idea 2)",
        "leader_name": "ARISH M",
        "mentor_name": "KISHORE K",
        "department": "B.Sc Digital & Cyber Forensic Science",
        "email": "arishm2425@ajkcas.com",
        "roll": "24UGDC002",
        "category": "Software",
        "ps": "[SIH26149] Block chain & Cyber Security"
    },
    {
        "sno": 49,
        "team_id": "SIH-TEAM-55",
        "team_name": "Viscams",
        "leader_name": "Deepak Dev S",
        "mentor_name": "Adhithiyan P",
        "department": "B.Sc Visual Communication & Electronics Media",
        "email": "deepakdevs2425@ajkcas.com",
        "roll": "24UGVC007",
        "category": "Software",
        "ps": "[SIH26089] Cooperative Gig Services Platform for Household & Community Services"
    },
    {
        "sno": 50,
        "team_id": "SIH-TEAM-56",
        "team_name": "Six Faces",
        "leader_name": "Varsha K",
        "mentor_name": "Suganya P",
        "department": "B.COM CA",
        "email": "varshak2425@ajkcas.com",
        "roll": "24UGCC026",
        "category": "Software",
        "ps": "[SIH26001] AI based early warning and landslide risk monitoring system in NER"
    },
    {
        "sno": 51,
        "team_id": "SIH-TEAM-57",
        "team_name": "Code Catalysts",
        "leader_name": "Amrutha Manoj",
        "mentor_name": "Muthusaravanan V",
        "department": "BCA Artificial Intelligence",
        "email": "amruthamanoj2526@ajkcas.com",
        "roll": "25UGAL009",
        "category": "Software",
        "ps": "[SIH26021] Honey Chain: A block chain-based system for honey traceability and smart beekeeping management."
    },
    {
        "sno": 52,
        "team_id": "SIH-TEAM-58",
        "team_name": "MindForge",
        "leader_name": "Ahamed roshan.A",
        "mentor_name": "Satchithanantham",
        "department": "B.Sc Computer Science with Data Analytics",
        "email": "ahamedroshan14@gmail.com",
        "roll": "24UGDA013",
        "category": "Software",
        "ps": "[SIH26044] Portal for Academia - Industry collaboration for Skill Mapping, Internships and Placement"
    },
    {
        "sno": 53,
        "team_id": "SIH-TEAM-59",
        "team_name": "Viscomers",
        "leader_name": "Thoufeeq",
        "mentor_name": "Adthithyan p",
        "department": "B.Sc Visual Communication & Electronics Media",
        "email": "thoufeeku2627@ajkcas.com",
        "roll": "6109",
        "category": "Software",
        "ps": "[SIH26089] Cooperative Gig Services Platform for Household & Community Services"
    },
    {
        "sno": 54,
        "team_id": "SIH-TEAM-60-B",
        "team_name": "Innovexa (Idea 2)",
        "leader_name": "Abinaya S",
        "mentor_name": "Mr.Kathirvelan",
        "department": "B.Sc Forensic Science",
        "email": "sabinaya2526@ajkcas.com",
        "roll": "25UGFS003",
        "category": "Software",
        "ps": "[SIH26204] Student Innovation"
    },
    {
        "sno": 55,
        "team_id": "SIH-TEAM-60-A",
        "team_name": "Innovexa (Idea 1)",
        "leader_name": "Abinaya S",
        "mentor_name": "Mr.Kathirvelan",
        "department": "B.Sc Forensic Science",
        "email": "sabinaya2526@ajkcas.com",
        "roll": "25UGFS003",
        "category": "Software",
        "ps": "[SIH26095] Smart Real-Time Monitoring & Inspection Mobile App"
    },
    {
        "sno": 56,
        "team_id": "SIH-TEAM-62-A",
        "team_name": "ThreatmailX (Idea 1)",
        "leader_name": "A.FATHIMA RIZWANA",
        "mentor_name": "KISHORE K",
        "department": "M.Sc Cyber Security",
        "email": "afathimarizwana2026@ajkcas.com",
        "roll": "5738",
        "category": "Software",
        "ps": "[SIH26106] AI-Powered Email Threat Detection, GeoLocation & Forensic Intelligence Platform"
    },
    {
        "sno": 57,
        "team_id": "SIH-TEAM-62-B",
        "team_name": "ThreatmailX (Idea 2)",
        "leader_name": "A.FATHIMA RIZWANA",
        "mentor_name": "KISHORE K",
        "department": "M.Sc Cyber Security",
        "email": "afathimarizwana2026@ajkcas.com",
        "roll": "5738",
        "category": "Software",
        "ps": "[SIH26155] AI-Driven Multi-Vendor Network Security Compliance Auditor"
    },
    {
        "sno": 58,
        "team_id": "SIH-TEAM-64-A",
        "team_name": "Cyphora (Idea 1)",
        "leader_name": "Akshaya Rajesh",
        "mentor_name": "KISHORE K",
        "department": "M.Sc Cyber Security",
        "email": "akshayarajesh2627@ajkcas.com",
        "roll": "5602",
        "category": "Software",
        "ps": "[SIH26104] AI-Powered Real-Time Detection and Prevention of Voice Cloning Impersonation Attacks and prevention of voice cloning impersonating attacks"
    },
    {
        "sno": 59,
        "team_id": "SIH-TEAM-64-B",
        "team_name": "Cyphora (Idea 2)",
        "leader_name": "Akshaya Rajesh",
        "mentor_name": "KISHORE K",
        "department": "M.Sc Cyber Security",
        "email": "akshayarajesh2627@ajkcas.com",
        "roll": "5602",
        "category": "Software",
        "ps": "[SIH26188] Al-Based Fake Identity & Document Screening System"
    },
    {
        "sno": 60,
        "team_id": "SIH-TEAM-66",
        "team_name": "VeriFrame",
        "leader_name": "Ashfaq Ashraf",
        "mentor_name": "Dr.Vineethavijayan",
        "department": "B.Sc Artificial Intelligence & Machine Learning",
        "email": "ashfaqashraf2526@ajkcas.com",
        "roll": "25UGAI012",
        "category": "Software",
        "ps": "[SIH26150] Development of a Multi-Vendor DVR/NVR Forensic Analysis Tool for Standardized Acquisition, Recovery, and Analysis of Surveillance Evidence"
    },
    {
        "sno": 61,
        "team_id": "SIH-TEAM-67-B",
        "team_name": "Raven Grove (Idea 2)",
        "leader_name": "Joshika s m",
        "mentor_name": "Kishore kannan",
        "department": "B.Sc Digital & Cyber Forensic Science",
        "email": "joshikasm2627@ajkcas.com",
        "roll": "26UGDC001",
        "category": "Software",
        "ps": "[SIH26188] Al-Based Fake Identity & Document Screening System"
    },
    {
        "sno": 62,
        "team_id": "SIH-TEAM-67-A",
        "team_name": "Raven Grove (Idea 1)",
        "leader_name": "Joshika s m",
        "mentor_name": "Kishore kannan",
        "department": "B.Sc Digital & Cyber Forensic Science",
        "email": "joshikasm2627@ajkcas.com",
        "roll": "26UGDC001",
        "category": "Software",
        "ps": "[SIH26104] AI-Powered Real-Time Detection and Prevention of Voice Cloning Impersonation Attacks"
    },
    {
        "sno": 63,
        "team_id": "SIH-TEAM-69",
        "team_name": "AI Pioneers",
        "leader_name": "Johen S John",
        "mentor_name": "K Shiny",
        "department": "BCA Artificial Intelligence",
        "email": "johensjohn2526@ajkcas.com",
        "roll": "25UGAL024",
        "category": "Software",
        "ps": "[SIH26070] To develop an Artificial Intelligence (AI) / Machine Learning (ML) based system for identification, classification, and prediction of different tropical cyclone patterns using multi-source satellite data."
    },
    {
        "sno": 64,
        "team_id": "SIH-TEAM-70",
        "team_name": "AI Mavericks",
        "leader_name": "Srinanth AK",
        "mentor_name": "Muthusaravanan V",
        "department": "BCA Artificial Intelligence",
        "email": "srinandhak2627@ajkcas.com",
        "roll": "5776",
        "category": "Software",
        "ps": "[SIH26229] Kabadiwala Connect \u2013 Bringing the Informal Collector into the Formal Recycling Chain"
    },
    {
        "sno": 65,
        "team_id": "SIH-TEAM-71",
        "team_name": "Mayhem",
        "leader_name": "Aysha parveen",
        "mentor_name": "Manobprabha",
        "department": "B.Sc Costume Design & Fashion",
        "email": "ayshaparveen2425@ajkcas.com",
        "roll": "24UGCD010",
        "category": "Hardware",
        "ps": "[26010] Survey/resurvey of rural agricultural land in India"
    },
    {
        "sno": 66,
        "team_id": "SIH-TEAM-72",
        "team_name": "Toss",
        "leader_name": "Shahana sherin V. V",
        "mentor_name": "G Manoprabha",
        "department": "B.Sc Costume Design & Fashion",
        "email": "shahanasherinvv2425@ajkcas.com",
        "roll": "24UGCD016",
        "category": "Hardware",
        "ps": "[SIH26005] Agriculture, FoodTech & Rural Development"
    },
    {
        "sno": 67,
        "team_id": "SIH-TEAM-73",
        "team_name": "Cybercore",
        "leader_name": "Lifa fathima F",
        "mentor_name": "Adharsh VP",
        "department": "BCA Cybersecurity with Data Science",
        "email": "lifafathimaf2627@ajkcas.com",
        "roll": "6218",
        "category": "Software",
        "ps": "[26005] Solar powered smart mini cold storage system for fresh vegetables in North eastern region ( NER)"
    },
    {
        "sno": 68,
        "team_id": "SIH-TEAM-74-A",
        "team_name": "CIPHERX (Idea 1)",
        "leader_name": "SRUTHI KEERTHI S S",
        "mentor_name": "Adarsh V P",
        "department": "BCA Cybersecurity with Data Science",
        "email": "sssruthikeerthi2627@ajkcas.com",
        "roll": "5706",
        "category": "Software",
        "ps": "[SIH26093] AI-Based Real-Time Stress and Trauma Assessment Module for Victims/Complainants Accessing NHAA (14566) and Integrated Portal"
    },
    {
        "sno": 69,
        "team_id": "SIH-TEAM-74-B",
        "team_name": "CIPHERX (Idea 2)",
        "leader_name": "SRUTHI KEERTHI S S",
        "mentor_name": "Adarsh V P",
        "department": "BCA Cybersecurity with Data Science",
        "email": "sssruthikeerthi2627@ajkcas.com",
        "roll": "5706",
        "category": "Software",
        "ps": "[SIH26124] AI-Powered Mobile Urban Intelligence Platform Using Public Transport Fleet"
    },
    {
        "sno": 70,
        "team_id": "SIH-TEAM-76",
        "team_name": "Pixel Pioneers",
        "leader_name": "Ayisha fasna M",
        "mentor_name": "Dr.M. Rajeshkumar",
        "department": "BCA Augmented Reality & Virtual Reality",
        "email": "ayishafasnam2425@ajkcas.com",
        "roll": "24UGAR005",
        "category": "Software",
        "ps": "[SIH26041] AR-Based Vocational Training Simulator for Industrial Safety in Jharkhand's Mining & Manufacturing Sector"
    },
    {
        "sno": 71,
        "team_id": "SIH-TEAM-71-1",
        "team_name": "Pixel Pioneers (2)",
        "leader_name": "Abhijith C",
        "mentor_name": "Dr. M. Rajeshkumar",
        "department": "BCA Augmented Reality & Virtual Reality",
        "email": "abhijithc2425@ajkcas.com",
        "roll": "24UGAR001",
        "category": "Software",
        "ps": "[SIH26067] Develop a web-based interactive 3D visualization platform that integrates numerical ocean model outputs and in-situ observations."
    },
    {
        "sno": 72,
        "team_id": "SIH-TEAM-72-A",
        "team_name": "Cipher Matrix (Idea 1)",
        "leader_name": "Amal Thomas",
        "mentor_name": "Ananthakrishnan U K",
        "department": "M.Sc Cyber Security",
        "email": "amalthomas2526@ajkcas.com",
        "roll": "25PGCY002",
        "category": "Software",
        "ps": "[SIH26190] Secure Digital Document Management System for Legal and Investigation Documents"
    },
    {
        "sno": 73,
        "team_id": "SIH-TEAM-72-B",
        "team_name": "Cipher Matrix (Idea 2)",
        "leader_name": "Amal Thomas",
        "mentor_name": "Ananthakrishnan U K",
        "department": "M.Sc Cyber Security",
        "email": "amalthomas2526@ajkcas.com",
        "roll": "25PGCY002",
        "category": "Software",
        "ps": "[SIH26152] Social Media Analytics"
    },
    {
        "sno": 74,
        "team_id": "SIH-TEAM-74",
        "team_name": "Nexora",
        "leader_name": "Shabika KA",
        "mentor_name": "Kishore k",
        "department": "B.Sc Digital & Cyber Forensic Science",
        "email": "shabika142@gmail.com",
        "roll": "5488",
        "category": "Software",
        "ps": "[SIH26044] Portal for Academia - Industry collaboration for Skill Mapping, Internships and Placement"
    },
    {
        "sno": 75,
        "team_id": "SIH-TEAM-75",
        "team_name": "MindMatrix",
        "leader_name": "Jenisha Sen",
        "mentor_name": "Mrs. K. Shiny",
        "department": "BCA Artificial Intelligence",
        "email": "jenishasen2627@ajkcas.com",
        "roll": "5770",
        "category": "Software",
        "ps": "[SIH26061] AI-Driven Smart Energy Management System for Polar Research Stations"
    },
    {
        "sno": 76,
        "team_id": "SIH-TEAM-76-1",
        "team_name": "Thadam @ AJK",
        "leader_name": "Divya Sri T",
        "mentor_name": "Mr.Kishore",
        "department": "M.Sc Cyber Security",
        "email": "dhivyasri01032006@gmail.com",
        "roll": "5086",
        "category": "Software",
        "ps": "[SIH26184] Development of a Predictive Analytics Framework for Cybercrime Complaints to Forecast Likely Cash Withdrawal"
    },
    {
        "sno": 77,
        "team_id": "SIH-TEAM-77",
        "team_name": "OptiFreight",
        "leader_name": "Avanthika P",
        "mentor_name": "Dr Poornima G",
        "department": "BBA Logistics & Supply Chain Management",
        "email": "avanthikap2526@ajkcas.com",
        "roll": "25UGBL019",
        "category": "Software",
        "ps": "[SIH26006] Transportation and logistics"
    },
    {
        "sno": 78,
        "team_id": "SIH-TEAM-78-A",
        "team_name": "Team warehouse (Idea 1)",
        "leader_name": "Raniya",
        "mentor_name": "Aromal",
        "department": "BBA Logistics & Supply Chain Management",
        "email": "raniyafathimac2627@ajkcas.com",
        "roll": "6082",
        "category": "Software",
        "ps": "[SIH26006] Storage and warehouse"
    },
    {
        "sno": 79,
        "team_id": "SIH-TEAM-78-B",
        "team_name": "Team warehouse (Idea 2)",
        "leader_name": "Raniya",
        "mentor_name": "Aromal",
        "department": "BBA Logistics & Supply Chain Management",
        "email": "raniyafathimac2627@ajkcas.com",
        "roll": "6082",
        "category": "Software",
        "ps": "[SIH26006] Storage and warehouse"
    },
    {
        "sno": 80,
        "team_id": "SIH-TEAM-78",
        "team_name": "ForenX",
        "leader_name": "Vineeah Krishna P",
        "mentor_name": "KISHORE K",
        "department": "B.Sc Digital & Cyber Forensic Science",
        "email": "vineeshkrishnap2526@ajkcas.com",
        "roll": "25UGDC054",
        "category": "Software",
        "ps": "[SIH26150] Development of a Multi-Vendor DVR/NVR Forensic Analysis Tool for Standardized Acquisition, Recovery, and Analysis of Surveillance Evidence."
    },
    {
        "sno": 81,
        "team_id": "SIH-TEAM-81",
        "team_name": "FARM TO LIVE",
        "leader_name": "Reshma M",
        "mentor_name": "Kishore k",
        "department": "B.Sc Digital & Cyber Forensic Science",
        "email": "reshmam2526@ajkcas.com",
        "roll": "25IGDC037",
        "category": "Software",
        "ps": "[SIH26032] Farmers often face long waiting times, lack of information regarding procurement schedules, and uncertainty about procurement status."
    }
]
};

if (typeof window !== "undefined") {
  window.INITIAL_DATA = INITIAL_DATA;
}
